### PR TITLE
update sharp, fix deprecation, drop node 6 & 8

### PR DESCRIPTION
**Pull request by nickschot**
`.withoutEnlargement()` was removed in sharp 0.22.0. It must now be passed as an option.

See: https://sharp.pixelplumbing.com/changelog#v0220---18supthsup-march-2019

### CODE REVIEW

**Comment by nickschot** [comment]
Oh! We need to drop node < 10 too for this version of sharp to work. Will update this PR asap...

**Comment by nickschot** [comment]
This should build now. Had to add a resolution for the nested sharp dep as ember-responsive-image is unfortunately outdated too. That should only really impact things when working on the addon though.

**Review by simonihmig — APPROVED** [review]
Thanks for working on this, Nick! And sorry that it took me so long to get back at this.

I invested my OSS day to day for getting the base addon polished up for a v1.0.0 release (long overdue 🙈). Strangely enough I do get segmentation faults there using the latest `sharp` (in Github CI): https://github.com/kaliber5/ember-responsive-image/pull/91

Will also do some more maintenance work here, we will see how this turns out...

**Comment by nickschot** [comment]
No worries! Thanks for continuing with the addon 😄 sharp is always a bit of a... picky dependency.

**Pull request merged**
